### ISSUE TITLE
Make rounded corner album art

### ISSUE THREAD

**Issue by y314315** [AudioBand/AudioBand#103]
Users can adjust the size of the rounded corners of the album art.
Just like this:
Switch ![image](https://user-images.githubusercontent.com/110112440/222683272-decc5990-0a75-436e-8b7e-6565ec3ff16f.png) into
![image](https://user-images.githubusercontent.com/110112440/222683424-e5dd1444-7781-4aeb-988a-87e27c92c127.png) or 
![image](https://user-images.githubusercontent.com/110112440/222684265-e0aa9e7f-fa54-43da-b4ed-cb5ba26c8693.png)
I would appreciate it if this proposal could be adopted.

**Comment by TechSupport26** [comment]
I am looking at implementing this and am curious if we should also be able to make the album art popup customisable as well.

**Comment by TechSupport26** [comment]
Currently, the corner radius for the AlbumArt it only works to a value of 20 at a size of 40 by 40 before there is no change in the corner radius. (This changes depending on the width and height)
(Here is a preview.) The current issue is that it is behind the album art and does not have an impact on the image. (There will be no colour behind the AlbumArt that is just to show where the Album Art will be visible.)
![image](https://user-images.githubusercontent.com/65631811/224478015-105b43ae-8718-40da-9c4f-9de6948dbc98.png)

**Comment by svr333** [comment]
I never saw the follow up message, sorry to hear you were stuck @TechSupport26 
Do you have the code for what you tried to make somewhere? Or should I try re-implementing this from scratch?

**Comment by TechSupport26** [comment]
Yes, I believe that what I have done is all here
https://github.com/TechSupport26/AudioBand/commits?author=TechSupport26

I switched to Linux so I am not able to run AudioBand on my computer but I have 2 virtual machines running windows 10 and 11 so I can do stuff from there.

I think that I had some local code but it was quite a while ago and I don't know if I saved it when I moved the data across.

You will also see some other commits on adding the MouseBinding for AudioSorce switching, I got stuck on that as well. Some of what I did is good but some of it is beyond my understanding.

**Comment by svr333** [comment]
I saw what you meant with being stuck, viewbox is an annoying control so I had to switch the ViewBox for a Border instead of just adding a border around it, which also meant I had to switch from Image to ImageBrush and rework it a bit, but I figured it out so it will be in the next release!
