### ISSUE TITLE
Renaming the Idle profile causes a crash 

### ISSUE THREAD

**Issue by TechSupport26** [AudioBand/AudioBand#107]
## Description
Renaming the Idle profile to something else and the back causes AudioBand to crash.
You can also delete the profile to crash AudioBand

The easiest way to fix this for the user is to have a back up and restore the AudioBand folder in AppData

## How To Reproduce
1. Open AudioBand Settings and select the Idle profile (You also can't select it from the task bar.)
2. Rename the profile and rename it back.
3. AudioBand will then crash.
5. See the log file.

Strangely this does not appear to affect windows 11 with explorer patch. (Can do further testing on request.)

## Version
 - Windows version 
Edition	Windows 10 Pro
Version	22H2
Installed on	‎19/‎04/‎2023
OS build	19045.2006
Experience	Windows Feature Experience Pack 120.2212.4180.0

 - AudioBand Version
v1.2.1

## Logs/Screenshots Attachment

[AudioBand delete Idle.log](https://github.com/AudioBand/AudioBand/files/11278740/AudioBand.delete.Idle.log)

If applicable, feel free to add screenshots to show us the issue.

**Comment by svr333** [comment]
Is probably missing a few checks to see if it is the idle profile, should not be too hard to fix (appsettings.cs)
