### ISSUE TITLE
“Custom Mouse Bindings” keep getting added upon reboot

### ISSUE THREAD

**Issue by sorsted** [AudioBand/AudioBand#111]
It seems that these are the default “Custom Mouse Bindings” in AudioBand:

![image](https://github.com/AudioBand/AudioBand/assets/50265631/4552755a-37af-4937-b4c9-a88914921cf1)

However, I prefer not having any custom mouse bindings at all (since I often accidentally use the scroll wheel while the mouse is hovering over the AudioBand taskbar). Therefore, I removed those “Custom Mouse Bindings”. However, whenever I reboot my PC, they’re back. I can then delete them again, but when I reboot again, same story.

**Comment by TechSupport26** [comment]
Good find.
A quick fix would be to add 1 mouse binding that uses eg. The middle mouse button.
If you then set it to double middle click and make it do something then the other bindings. Select all the options to require an additional button to make it less likely to happen.
Doing this will stop the other mousebindings from appearing after a reboot.
