### ISSUE TITLE
Crash when trying to edit default profile

### ISSUE THREAD

**Issue by vvyushmanov** [AudioBand/AudioBand#113]
## Description
Attempting to edit/open Default profile in Setting results in crash

## How To Reproduce
1. Enable AudioBand toolbar
2. Right-click -> switch to Default profile
3. Right-click -> click settings

After this Windows Explorer restarts, the logs contain the following exception:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at MS.Internal.FontCache.FontFaceLayoutInfo.IntMap.TryGetValue(Int32 key, UInt16& value)
   at System.Windows.Media.GlyphTypeface.Initialize(Uri typefaceSource, StyleSimulations styleSimulations)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.InitializationGuard(XamlType xamlType, Object obj, Boolean begin)
   at System.Xaml.XamlObjectWriter.Logic_EndInit(ObjectWriterContext ctx)
   at System.Xaml.XamlObjectWriter.WriteEndObject()
   at System.Windows.Markup.WpfXamlLoader.TransformNodes(XamlReader xamlReader, XamlObjectWriter xamlWriter, Boolean onlyLoadOneNode, Boolean skipJournaledProperties, Boolean shouldPassLineNumberInfo, IXamlLineInfo xamlLineInfo, IXamlLineInfoConsumer xamlLineInfoConsumer, XamlContextStack`1 stack, IStyleConnector styleConnector)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
...
```

## Version
ersion: "v1.2.1", OS: Microsoft Windows NT 10.0.19045.0 (Windows 10 22H2)

## Logs/Screenshots Attachment
[AudioBand.log](https://github.com/AudioBand/AudioBand/files/12241494/AudioBand.log)

If applicable, feel free to add screenshots to show us the issue.

**Comment by svr333** [comment]
Thanks for taking time to report the issue!

At a first look at the stacktrace, it looks like either an internal error in WPF (which I have never seen) or, furtherdown in the stacktrace it mentions ResourceDictionaries which can mean that there is a value missing somewhere on our end, but it seems unlikely.

I dont think I can do much to fix this issue without having your profile, would you mind sending it over?
It is located in `%appdata%/AudioBand/Profiles/Default Profile.json`.

### Possible attempt to fix it:
Delete the entire `%appdata%/AudioBand` folder (or only `%appdata%/AudioBand/Profiles` if you dont want to lose your settings)

**Comment by vvyushmanov** [comment]
Hi!

Thanks for the reply.
I've already tried cleaning up the appdata, this did not fix the issue.
Anyway, here are all my profiles (Default is slightly modified, Volume and Like switched places)
[Profiles.zip](https://github.com/AudioBand/AudioBand/files/12242463/Profiles.zip)

I've also tried deleting the settings with the same result.

A couple more details:
1) There were no issues initially, issues started after some tinkering with the profile settings (at first, profile was not updating in realtime, and then this bug began to happen)
2) The only source I have set up is Spotify, the issue reproduces both with it launched and not launched
3) Currently, there are 4 profiles available:
![image](https://github.com/AudioBand/AudioBand/assets/111231219/0c86081d-f68e-4621-9caf-a5785342b655)

- When no profile is selected, settings open fine
- Switching to default/compact/default (compact) works fine, but opening the settings generate the mentioned error
- Switching to "No controls" immediately crashes the app, even before trying to open the settings
- Turning the audio source off/on does not affect the issue

Also, for some reason, I have several instances of explorer after the crashes:
![image](https://github.com/AudioBand/AudioBand/assets/111231219/24e92aa9-45a0-452b-b288-0e1e504e0f2f)

Force-stopping and relaunching explorer.exe has no effect

**Comment by vvyushmanov** [comment]
Oh, one more thing, the following steps also generate the crash:
1. Enable the toolbar
2. Open the settings (while Idle)
3. Change to any profile in the settings window

**Comment by svr333** [comment]
It could maybe be a font issue but it sounds very weird. The default profile uses a default Windows font.
So if it is the font then it could either be that you or some app uninstalled the windows font that the settings menu uses or that something went wrong with the audioband install.

I can recommend a full clean install, as in deleting the `%appdata%/AudioBand` folder and then uninstalling and reinstalling, but if that doesnt work I will dig a bit deeper to see if I can find a cause

**Comment by vvyushmanov** [comment]
Tried the clean reinstall - nothing changed, sadly.
Please let me know if I can provide any additional information.

**Comment by svr333** [comment]
I've looked a bit deeper and I can't find anything. The profiles you sent are a 1 on 1 copy of the default profiles, so they cannot be the issue.
It says you're using AudioBand version 1.2.1, so that looks fine too (I assume you installed it from the releases page on github)

Your windows version is 4 patch versions more updated than mine, but that should not make the difference (because we'd get a lot more reports)
Are you running a custom/modified windows iso? (things like AtlasOS or similar)

If it's none of these, then the only way to really debug this is to install visual studio and run AudioBand in Debug (developer) mode and see exactly where it crashes. But this requires both coding knowledge and some time

**Comment by vvyushmanov** [comment]
Hi,

No, I am running a clean Windows 10 Pro, licensed, no mods as far as I'm concerned.

I have some coding experience (junior-level Kotlin and Python, I am a QA automation engineer), so I think this is doable and I'll gladly assist in debugging.
Please let me know how I can reach out to you directly to coordinate. From the docs I understand I need to install VS 2019?

**Comment by vvyushmanov** [comment]
Okay, so I've read some articles out and about, thinking that the issue is connected to my Fonts cache and system fonts in General.
Luckily, I've come across [this article](https://woshub.com/how-to-restore-default-fonts-in-windows-8-1/) that gives detailed steps to reset and restore Windows 10/11 Font cache.

After following all steps, it all works fine now, finally!

Thank you for your time, and my apologies - the issue was on my machine all along.

**Comment by svr333** [comment]
Forgot to continue responding to this, sorry!
Glad the issue got resolved and will keep it in mind if anyone else has it in the future!
