### ISSUE TITLE
Spotify like button malfunctioning

### ISSUE THREAD

**Issue by karimawii** [AudioBand/AudioBand#114]
## Description
A lot of times a song is already liked and it shows as not liked in audioband, you have to like the song while you're listening to it for audioband to color the heart
## How To Reproduce
1. Play an already liked song
2. There's a pretty good chance audioband doesn't have the heart colored

## Version
 - Windows 10 version 22H2 Build 19045.3208
 - AudioBand Version 1.2.1

**Comment by svr333** [comment]
This issue is weird but can be caused due to changes in the api/a bug in our code.
I have some additional questions if you don't mind me asking:

1) Do you run any Spotify modifications (like spicetify for example)
2) Do you have Spotify Premium?

**Comment by karimawii** [comment]
I do have Spicetify but I never had any issues with it not connecting to Spotify Connect, I've used Spotify API in a bunch of applications and all my testing was on a modded Spotify client with Spicetify, I don't recall having any issues regarding the like button or playback, and yes I have Spotify premium.

Here's my current versions of Spotify and Spicetify
```
Spotify 1.2.17.834.g26ee1129
Spicetify v2.22.1
```

**Comment by svr333** [comment]
Sorry for the delay! I'm currently pretty busy in life so I don't have much time this summer for AudioBand.

I tried to reproduce your issue but I was unavailable to do so. I am running the exact same Spotify and Spicetify versions as you and it works perfectly for me.
The only thing I did notice is that if you are playing a song that you have liked, and then play a local song (which cannot be liked) the liked heart will stay toggled on.

One thing that can be happening is that you are getting rate-limited. I think if I remember correctly that I used to have my `Spotify Polling Interval` (in AudioBand Settings ->AudioSource Settings -> Spotify) set to 750 and then I got warnings in the `AudioBand.log` file that I was being ratelimited.

Could you check if you can see any error messages related to this in the `AudioBand.log` file (located in the `%temp%` folder?
If this isn't the case, I will take a deeper look at this when I have more time, but most likely not before the end of this month.

**Comment by karimawii** [comment]
Hey, thanks for the reply, you're I hop life's going well for you, I increased the polling rate to 1500 milliseconds and it's working great so far. Thanks for helping.
