### ISSUE TITLE
Nilesoft Shell is incompatible with AudioBand

### ISSUE THREAD

**Issue by prism2001** [AudioBand/AudioBand#132]
## Description
if [nilesoft shell](https://nilesoft.org/docs) is being used, AudioBand fails to load. additionally, the right click menu for toolbars does not appear under nilesoft shell. if you try and deregister nilesoft, enable the audioband toolbar and then re-enable nilesoft, audioband still fails to appear

(for context, nilesoft shell is a right-click menu replacement for 11 that retains the style of 11's context menu, but returns all the options that were hidden behind "More options", and is much more configurable)

i don't know if this is something that can be fixed on the audioband side, or if the devs of Shell have to fix it, or if it's simply a limitation of Windows

## How To Reproduce
1. Have Nilesoft Shell installed and activated
2. Have AudioBand installed
3. AudioBand will not appear in the taskbar as long as Shell is registered

## Version
 - Windows 11 23H2, 22631.3155
 - AudioBand v1.2.3
 - Nilesoft Shell v1.9.15

## Logs/Screenshots Attachment
(Log file does not contain any sort of error or other helpful info regarding the issue, so it will be omitted)

**Comment by svr333** [comment]
This is weird because it works perfectly fine for me with Nilesoft Shell. Though I do also have StartAllBack installed as well.
Maybe try combining the 2?

![image](https://github.com/AudioBand/AudioBand/assets/35664724/49ff3dab-1ab8-428c-bc46-3a2c4d15b798)

**Comment by prism2001** [comment]
> This is weird because it works perfectly fine for me with Nilesoft Shell. Though I do also have StartAllBack installed as well. Maybe try combining the 2?

unfortunately this didn't work either. it seems that Shell gets rid of the right-click option on the taskbar that allows you to put toolbars (which AudioBand is) on the taskbar

**Comment by TechSupport26** [comment]
I am using ExplorerPatch

For me I don't have the shell option at the top when right clicking to even add AudioBand to the taskbar. However as I already had it installed nilesoft shell did not initially remove it from the taskbar but I have no option to add or remove toolbars (AudioBand)

Does AudioBand come up on the taskbar at all when nilesoft is not registered and StartAllBack is installed?

**Comment by prism2001** [comment]
> Does AudioBand come up on the taskbar at all when nilesoft is not registered and StartAllBack is installed?

yes, but the moment i re-register nilesoft and restart explorer, audioband disappears again

**Comment by svr333** [comment]
This is weird as for me it doesn't remove once I activate nilesoft, sadly this is more likely an issue on their end as they have to have support for toolbars.
Maybe try completely uninstalling shell and reinstalling? Cause it does work perfectly fine for me, even after I register nilesoft

**Comment by prism2001** [comment]
i have decided to just uninstall nilesoft for now. it's not a solution to the actual problem but i can live without it

**Comment by prism2001** [comment]
today i uninstalled StartAllBack and tried EP+AudioBand again and it is working, so i am closing this issue
