### ISSUE TITLE
Not working in Windows 11

### ISSUE THREAD

**Issue by MaxiAxi-Jorn** [AudioBand/AudioBand#134]
## Description
Can't get it to work in Windows 11, without changing my task bar into the Windows 10 design.
I've installed the ExplorerPatcher, but I've got no option to add AudioBand to the taskbar when using the normal Windows 11 task bar.

Or is it only possible with the Windows 10 task bar? That's clear for me in the [Windows 11 instructions](https://audioband.github.io/AudioBand/audioband/Windows11.html).

## How To Reproduce
1. Install AudioBand
2. Install ExplorerPatcher
3. Do not change any ExplorerPatcher settings
4. No AudioBand available in the task bar (also not available when right-clicking)

## Version
- Windows 11 Pro 23H2 22631.3296
- AudioBand Version 1.2.3

## Logs/Screenshots Attachment

[AudioBand.log](https://github.com/AudioBand/AudioBand/files/14803211/AudioBand.log)

**Comment by svr333** [comment]
I think with ExplorerPatcher it only works on the windows 10 bar, while with StartAllBack it should work on a "fake" windows 11 bar, its basically a restyled windows 10 bar to look exactly like windows 11 iirc.

I haven't updated the docs because I haven't done the research either and I should get to it at some point

**Comment by MaxiAxi-Jorn** [comment]
Hi @svr333. Thank your for your reply.
That's not what I'm looking for then, I want to keep using 'the real' Win11 bar. Hopefully you've get some time in the future to update this, because I do like the software!

**Comment by svr333** [comment]
@MaxiAxi-Jorn all right! The fake windows bar looks and functions just like it though with StartAllBack.
For an alternative to using such software I'm afraid it wont be a thing anytime soon, as it would be a lot of work and I'm currently just doing (critical) bug fixes whenever I have some extra time
