### ISSUE TITLE
Progress Bar updating every three seconds.

### ISSUE THREAD

**Issue by SSII77** [AudioBand/AudioBand#139]
## Description
After updating to the latest version, playing music from Spotify updates the progress bar every three seconds, whereas on the previous version it would update every second. 

## How To Reproduce
1. Play music from Spotify

## Version
Windows 10 Pro 22H2
AudioBand Version 1.2.3

## Logs/Screenshots Attachment
N/A

**Comment by svr333** [comment]
Some questions:
1) Do you have Spotify open on the device that is running audioband?
2) Do you have Spotify Premium?
3) What is your polling interval set to? (Settings -> Audiosource settings -> Spotify -> Spotify polling interval)

**Comment by SSII77** [comment]
1. Spotify is running on the same device as AudioBand
2. I do have Premium
3. Polling interval is set to 1000

**Comment by svr333** [comment]
Very weird, when for example running spotify on your phone and you are on your pc but do not have the spotify app open, it will default to 3 seconds to prevent hitting the ratelimit.

While I was writing this I saw my own Spotify also only updating every 3 seconds, so it's definitely a bug somewhere (it could also be Spotify updating their ratelimit so you're not allowed to fetch it as often)
I'll try to look into it when I have some time

**Comment by svr333** [comment]
Ah one more question, do you use Spicetify?

**Comment by SSII77** [comment]
I see so it's probably a change on their end. Also no I don't use Spicetify.

**Comment by svr333** [comment]
Likely but I'll look into it, could also be a bug on our end if it only break when you updated to the latest audioband version

**Comment by svr333** [comment]
All right I found the issue, we used a certain way of finding which window on your pc is the Spotify window and they changed some naming, so it couldn't find the window properly therefore AudioBand defaulted to a 3 second delay.

I will create a new release in a bit and you should be able to update audioband from within the app

**Comment by svr333** [comment]
https://github.com/AudioBand/AudioBand/releases/tag/v1.2.4
