### ISSUE TITLE
AudioBand with StartAllBack doesn't work on Windows 11 anymore.

### ISSUE THREAD

**Issue by duanxr** [AudioBand/AudioBand#149]
## Description
I use windows 11 and fixed the taskbar with StartAllBack . They worked fine, but recently they doesn't work anymore suddenly.
AudioBand no longer shows up, and there is no option about AudioBand in the right-click taskbar menu.
I've tried  to reinstall, repaire AudioBand and StartAllBack but they still don't work, any clues?

## Version
 - Windows version Windows 11 24H2 26100.2033
 - AudioBand Version v1.2.4 Latest
 - StartAllBack 3.8.11

## Logs/Screenshots Attachment
I tried but there's no any log files.

**Comment by OgLemons** [comment]
I haven't been able to get it to install in the first place, I am running 23H2.

**Comment by Talafhah1** [comment]
also getting the same issue

**Comment by gabrieldevsouza** [comment]
Same here on Windows 11 24H2

**Comment by Popslip** [comment]
Can't install, "network resource unavailable".

**Comment by legofanlovessayori** [comment]
![image](https://github.com/user-attachments/assets/1170af02-3c55-4bdb-911d-942712154817)

Works here, to me it seems like its just a corrupt msi that you guys got.

**Comment by erythroz** [comment]
> ![image](https://private-user-images.githubusercontent.com/94994630/396401811-1170af02-3c55-4bdb-911d-942712154817.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0ODM5NTksIm5iZiI6MTczNDQ4MzY1OSwicGF0aCI6Ii85NDk5NDYzMC8zOTY0MDE4MTEtMTE3MGFmMDItM2M1NS00YmRiLTkxMWQtOTQyNzEyMTU0ODE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE4VDAxMDA1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmNDdlMmYzYzE0MDg1MTJiM2ViYzI5YTM2ZTI0MDg2OWVmZjljOTVmYmQ5OGQyYjRjOTQ1MDBmYWVlNGM1MmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1LlDy-Rha9KYykcnAJDFhv5PQo7EmT9GMsTtWjLojMo)
> 
> Works here, to me it seems like its just a corrupt msi that you guys got.

Just tried to install it as well on W11 24H2 (GhostSpectre Windows) with StartAllBack, not working, I do not get any option for AudioBand on a right click on the ToolBar.

**Comment by legofanlovessayori** [comment]
> > ![image](https://private-user-images.githubusercontent.com/94994630/396401811-1170af02-3c55-4bdb-911d-942712154817.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0ODM5NTksIm5iZiI6MTczNDQ4MzY1OSwicGF0aCI6Ii85NDk5NDYzMC8zOTY0MDE4MTEtMTE3MGFmMDItM2M1NS00YmRiLTkxMWQtOTQyNzEyMTU0ODE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE4VDAxMDA1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmNDdlMmYzYzE0MDg1MTJiM2ViYzI5YTM2ZTI0MDg2OWVmZjljOTVmYmQ5OGQyYjRjOTQ1MDBmYWVlNGM1MmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1LlDy-Rha9KYykcnAJDFhv5PQo7EmT9GMsTtWjLojMo)
> > Works here, to me it seems like its just a corrupt msi that you guys got.
> 
> Just tried to install it as well on W11 24H2 (GhostSpectre Windows) with StartAllBack, not working, I do not get any option for AudioBand on a right click on the ToolBar.

It doesn't show instantly after installing, you have to open the Toolbar menu a second time after it got installed.
And you need to unlock your taskbar on SAB to be able to add Toolbars.

**Comment by Waliactico** [comment]
Same thing happening here, there's no option to add toolbars now. Anyone found a workaround?

**Comment by legofanlovessayori** [comment]
> Same thing happening here, there's no option to add toolbars now. Anyone found a workaround?

Unlock your ta
![vmware_gCRJzcUZyn](https://github.com/user-attachments/assets/e78a68a7-725a-4e01-ba59-260c70b25416)
skbar.

**Comment by duanxr** [comment]
> > Same thing happening here, there's no option to add toolbars now. Anyone found a workaround?
> 
> Unlock your taskbar. ![vmware_gCRJzcUZyn](https://private-user-images.githubusercontent.com/94994630/397886400-e78a68a7-725a-4e01-ba59-260c70b25416.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3NTM0NTAsIm5iZiI6MTczNDc1MzE1MCwicGF0aCI6Ii85NDk5NDYzMC8zOTc4ODY0MDAtZTc4YTY4YTctNzI1YS00ZTAxLWJhNTktMjYwYzcwYjI1NDE2LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIxVDAzNTIzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhYWFkYWEwNDhhZjg4ZmIzMWU0NGQyNDRlMTE4MjYzZDNlYTIzODEyY2RjZDQzOGNhYTc3NDI0YmNjMTI1NDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.t3gTiUpHm6tMxlXmrOkiXtE-G76J5CBZDRaUzDIEFV4) [ ![vmware_gCRJzcUZyn](https://private-user-images.githubusercontent.com/94994630/397886400-e78a68a7-725a-4e01-ba59-260c70b25416.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3NTM0NTAsIm5iZiI6MTczNDc1MzE1MCwicGF0aCI6Ii85NDk5NDYzMC8zOTc4ODY0MDAtZTc4YTY4YTctNzI1YS00ZTAxLWJhNTktMjYwYzcwYjI1NDE2LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIxVDAzNTIzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhYWFkYWEwNDhhZjg4ZmIzMWU0NGQyNDRlMTE4MjYzZDNlYTIzODEyY2RjZDQzOGNhYTc3NDI0YmNjMTI1NDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.t3gTiUpHm6tMxlXmrOkiXtE-G76J5CBZDRaUzDIEFV4) ](https://private-user-images.githubusercontent.com/94994630/397886400-e78a68a7-725a-4e01-ba59-260c70b25416.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3NTM0NTAsIm5iZiI6MTczNDc1MzE1MCwicGF0aCI6Ii85NDk5NDYzMC8zOTc4ODY0MDAtZTc4YTY4YTctNzI1YS00ZTAxLWJhNTktMjYwYzcwYjI1NDE2LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIxVDAzNTIzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhYWFkYWEwNDhhZjg4ZmIzMWU0NGQyNDRlMTE4MjYzZDNlYTIzODEyY2RjZDQzOGNhYTc3NDI0YmNjMTI1NDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.t3gTiUpHm6tMxlXmrOkiXtE-G76J5CBZDRaUzDIEFV4) [ ](https://private-user-images.githubusercontent.com/94994630/397886400-e78a68a7-725a-4e01-ba59-260c70b25416.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3NTM0NTAsIm5iZiI6MTczNDc1MzE1MCwicGF0aCI6Ii85NDk5NDYzMC8zOTc4ODY0MDAtZTc4YTY4YTctNzI1YS00ZTAxLWJhNTktMjYwYzcwYjI1NDE2LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIxVDAzNTIzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhYWFkYWEwNDhhZjg4ZmIzMWU0NGQyNDRlMTE4MjYzZDNlYTIzODEyY2RjZDQzOGNhYTc3NDI0YmNjMTI1NDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.t3gTiUpHm6tMxlXmrOkiXtE-G76J5CBZDRaUzDIEFV4)

OMG, it works for me, thank you

**Comment by MBS17** [comment]
> > Same thing happening here, there's no option to add toolbars now. Anyone found a workaround?
> 
> Unlock your taskbar.

After I click "audioband" in Toolbars, my taskbar freezes...
