### ISSUE TITLE
Spotify first time Auth not working

### ISSUE THREAD

**Issue by svr333** [AudioBand/AudioBand#26]
## Description
This issue is taking a while to solve as I cannot find the origin of it, therefore there'll be a guide on how to solve it below.  
The actual issue is that when you create a new app on the Spotify Dashboard, AudioBand doesn't have enough permission to allow the user who made the app to use it, which is quite weird.

The exact error given is `User not registered in the Developer Dashboard`.

## Manual Fix
1) Go to the Spotify Dashboard -> log in -> go to your AudioBand app -> Add `https://getyourspotifyrefreshtoken.herokuapp.com/callback` to your redirect urls.
2) Go to https://getyourspotifyrefreshtoken.herokuapp.com/ and enter your client id and secret there.
3) Select the following scopes and press submit, you will receive your Spotify Refresh Token
![image](https://user-images.githubusercontent.com/35664724/140389037-5f1315b4-bede-4aba-9181-7d3e9b44076d.png)
4) Go to AudioBand Settings -> About -> Open Settings Folder (file explorer should open)
5) Open `settings.json`, look for the setting called: `Spotify Refresh Token` and change it to be as followed: (underneath the red line you have to paste your Refresh Token received from the external site)
![image](https://user-images.githubusercontent.com/35664724/140389462-2fe018c9-dd49-4d08-a558-8dc8654a73b1.png)

## Permanent Fix
So far I've tried changing around the settings on the Dashboard, yields were unsuccessful however.  
I've tried adding my own account's email to the allowed users and tried changing the redirect urls.

On my main Spotify Account I can reset my authentication without issue, but it has Extended Quota on the Dashboard, while the new app doesn't and that fails.

I'll try to fix this issue soon as it is quite annoying.

**Comment by svr333** [comment]
This issue should be taken care of; Long story short; It only happens when you have 2 accounts on the same desktop and you login with the wrong one

**Comment by pakoito** [comment]
Heroku is going down shortly, you may need an alternative deploy.
