### ISSUE TITLE
Add custom mouse operations

### ISSUE THREAD

**Issue by zuoxinyu** [AudioBand/AudioBand#35]
Hi, glad to find such a project with great features and complete implementation. I wrote a similiar [deskband](https://github.com/zuoxinyu/GlobalMediaControl) but encountered some critical bugs I'd no idea to fix them.

## Description of your Suggestion

I'm used to select the `No Controls` profile, but with this I can't control current playing status. It would be better if there was a way to define some custom operations on the title or album area such as:

- mouse scroll up/down to switch songs
- middle click to pause/resume playing
- double click to traverse through profiles

## Alternative Solutions
It can be done by defining global keymappings in different music apps. 

## Extra (if applicable)
Add transition animations during switching songs.

**Comment by svr333** [comment]
Thank you for you the feedback, I could definitely see myself implementing the mouse keybinds.
(though double click is already in use for opening up the corresponding player (unless you're on Windows 10 audiosource)

Regarding your extra comment, how would you suggest on implementing transition animations?

**Comment by zuoxinyu** [comment]
> Thank you for you the feedback, I could definitely see myself implementing the mouse keybinds.
> (though double click is already in use for opening up the corresponding player (unless you're on Windows 10 audiosource)
> 

Thanks, I'll figure it tomorrow.

> Regarding your extra comment, how would you suggest on implementing transition animations?

Just a sliding up/down or fading in/out would be nice? I'll try to impl it and make a pr if I had spare time someday.

**Comment by svr333** [comment]
> I'll try to impl it and make a pr if I had spare time someday.

Thatd be amazing :) Im quite bad with animations in WPF so it would probably take me a long while to figure out

**Comment by svr333** [comment]
Im getting there :)

![image](https://user-images.githubusercontent.com/35664724/163233827-11755c62-d43e-4b6e-acb8-5f9da34d0402.png)
