### ISSUE TITLE
Add 💚 button for spotify 

### ISSUE THREAD

**Issue by kolinekp** [AudioBand/AudioBand#43]
As a user, I want to be able to mark song as favorite in the toolbar. (Click the 💚 icon)

**Comment by giaaaacomo** [comment]
i was about to forward the same idea! +1

**Comment by Switcherooo** [comment]
If it's desired to be a more "general" feature it could also mark as favorite as most music services (and local playback apps like VLC) support some kind of favorites/liked songs. +1

**Comment by HKC001** [comment]
I love this idea.

**Comment by TechSupport26** [comment]
This should be implimented soon -> Pull Request #76 
Spotify will only work for premium accounts.
I am working on adding this to iTunes at the moment.
