### ISSUE TITLE
Progress bar drag/click does not change song position

### ISSUE THREAD

**Issue by FoxcroftN** [AudioBand/AudioBand#47]
## Description
When dragging the progress bar the song does not update to the required location. 

## How To Reproduce
1. Click/Drag the progress bar to a relevant position. 
2. Song Pauses or restarts.
3. Problem was found with Spotify as the source and Windows 10 as the source.

## Version
 - Windows version: 21H2
 - AudioBand Version: v1.1.1

## Logs/Screenshots Attachment
(https://github.com/AudioBand/AudioBand/files/8013986/AudioBand.log)

Song progress - Before click
![image](https://user-images.githubusercontent.com/70165782/152762002-ddcd4bce-8ae6-46fb-94ef-0b0b06a37b15.png)

Song progress - After clicking "30sec" ahead
![image](https://user-images.githubusercontent.com/70165782/152762082-aa7940a7-5f5f-4684-8b58-e084fa1428f0.png)

**Comment by svr333** [comment]
Thank you for the report, Ill try to reproduce and find a fix soon

**Comment by svr333** [comment]
Some extra information I might need:
1. Do you have Spotify Premium?
2. What app did you use together with the Windows 10 audiosource?

**Comment by FoxcroftN** [comment]
I have Spotify Premium but have not set up my Spotify Audio Source on this PC as I default to the Windows Audio source.

I use Spotify, Deezer, YouTube and YouTube Music with the windows audio source (not at the same time)

App's Behaviors when Seeking using Progress Bar:

Spotify: Restarts the song from the beginning
Deezer: Nothing (Progress bar does not display progress)
YouTube (Through browser): Nothing (Progress bar does not display progress)
YouTube Music: Nothing (Progress bar does not display progress)


I might be wrong in assuming that the seek functionality is available with windows 10 as the audio source. Just starting to try and contribute to this project.

**Comment by svr333** [comment]
> I might be wrong in assuming that the seek functionality is available with windows 10 as the audio source. Just starting to try and contribute to this project.

Don't worry about that, I always appreciate feedback. It helps a lot if people report stuff.

### Spotify
I was able to reproduce with Spotify as music source together with Windows 10 audiosource.
This is a bug and I'll look into it, the song should not begin at 0 when you try to seek.

### Others
Regarding the others, with the Windows 10 API it is up to the apps to implement it, we cannot add specific support.
It appears that both Deezer and YouTube Music don't have a lot of support for the API as of currently.

Browsers (Firefox and any Chromium based (Chrome, MS Edge, ...)) support everything apart from Shuffle, Repeat and Timeline (progress bar).

You can use [This Page](https://github.com/ModernFlyouts-Community/ModernFlyouts/blob/main/docs/GSMTC-Support-And-Popular-Apps.md) to see which apps support which features (though Deezer and YouTube Music arent on there yet, but Ill make sure it gets on there)

**Comment by svr333** [comment]
Found the issue
Resolved by [46b59af](https://github.com/AudioBand/AudioBand/commit/46b59afbd9d4435ced507c66dfe8b7b406649ad2)
