### ISSUE TITLE
Infinite Auth/API Loop

### ISSUE THREAD

**Issue by TrySpace** [AudioBand/AudioBand#52]
## Description
The spotify api was offline which resulted in an aggressive re-authentication loop that opened a browser tab about every second. (The end of the url: `response_type%3Dcode%26redirect_uri%3Dhttp%253A%252F%252Flocalhost%253A80%26state%3D55f18fa9%26scope%3Duser-read-playback-state%2520user-modify-playback-state%2520user-read-currently-playing%26show_dialog%3DFalse`)
I had to kill explorer.exe to stop this.
After restarting explorer it only opened the tab once.

## How To Reproduce
Probably going offline won't reproduce, but perhaps an unknown api error would?

### Temporary fix
Update code to have a delay of at least a few seconds after api auth fails

## Version
 - Windows version 1909 (18363.1556)
 - AudioBand Version 0.9.4

**Comment by phit** [comment]
just ran into the same issue, can confirm killing explorer does help for now

**Comment by Jan1torEarl** [comment]
Yeah Spotify is having major problems ATM it seems. Also found removing the "Spotify Client ID" under `Audiosource settings > Spotify` prevents loop for now. Of course you'll need to put back in your client id once it's back up which can be found in [Spotify Dashboard](https://developer.spotify.com/dashboard/login), as mentioned [in the docs](https://audioband.github.io/AudioBand/audioband/audiosources/spotify.html).

**Comment by svr333** [comment]
Ill get a fix going for this issue soon, thanks for the reports and sorry for the inconvenience

**Comment by svr333** [comment]
Well that was fast, issue should be resolved in future updates

For the interested:
The issue was that I never really checked if Spotify was online and functioning properly.
I just have to add a fail check to see if something goes wrong on Spotify's end, that AudioBand still handles it in a friendly way.

**Comment by svr333** [comment]
Though I also recommend updating (just noticed your AudioBand version is 0.9.4)
