### ISSUE TITLE
The color of the play/pause button applies to all profiles

### ISSUE THREAD

**Issue by adinklotz** [AudioBand/AudioBand#54]
## Description
Changing the color of the play/pause button changes its color across all profiles, not just the selected one.
## How To Reproduce
1. Open Settings
2. Select some profile from the dropdown 
3. Go to Profile Settings > Buttons > Play/Pause Button
4. Change the text color settings to a different color and hit Apply
6. Switch to a different profile
7. The changed color is applied not just to the selected profile, but when you change profiles it is also included in the other profiles

The play/pause button is the only place I've noticed this. Text color of the text labels is set per-profile, but play/pause button color seems to be global. Because of this inconsistency I assume this is not intended functionality

## Version
- Windows 10 19044.1586
- AudioBand v1.1.2

## Logs/Screenshots Attachment
[AudioBand.log](https://github.com/AudioBand/AudioBand/files/8317418/AudioBand.log)

If applicable, feel free to add screenshots to show us the issue.

**Comment by svr333** [comment]
Was able to reproduce, thank you for reporting Ill get working on a fix soon!

**Comment by svr333** [comment]
Issue is resolved, will be in the next release
