### ISSUE TITLE
Spotify login loop: malformed url

### ISSUE THREAD

**Issue by pakoito** [AudioBand/AudioBand#57]
## Description

A malformed `redirect_url` is causing my install to fail to use Spotify. The trailing `/` added to the URL, maybe by Spotify themselves, causes the callback to fail with `INVALID_CLIENT: Invalid redirect URI`.

Manually fixing the URL passes the auth check, but any subsequent rechecks trigger the error again.

Current:
https://accounts.spotify.com/authorize?client_id=XXXXXX&response_type=code&redirect_uri=http://localhost:6565/&scope=user-read-currently-playing+user-read-playback-state+user-read-playback-position+user-modify-playback-state

Expected
https://accounts.spotify.com/authorize?client_id=XXXXXX&response_type=code&redirect_uri=http://localhost:6565&scope=user-read-currently-playing+user-read-playback-state+user-read-playback-position+user-modify-playback-state

## How To Reproduce
1. Add Spotify Account
2. Select Spotify Source
3. See terminal spawn
4. See OAUTH connection fail

## Version
 - Windows version: 10
 - AudioBand Version: 1.1.2

**Comment by pakoito** [comment]
Spotify's config:

![2022-04-14 01_25_58-My Dashboard _ Spotify for Developers — Mozilla Firefox](https://user-images.githubusercontent.com/514871/163290688-ff43721a-15d0-4c6b-b8fe-f03ce909f062.png)

**Comment by svr333** [comment]
This is probably a side effect of having a custom port set during auth. Ill take a look tomorrow and fix it up.

In case you want to get it fixed now you can follow [The manual guide](https://github.com/AudioBand/AudioBand/issues/26) here or you can change the callback port to default (80).  
Thanks for taking your time to report it!

**Comment by pakoito** [comment]
Thank you for the fast response. After some fiddling and a reboot I made it work with your guide. Don't edit the settings file live hehehe

I kept the callback as http://localhost:6565 just in case :D

**Comment by rZiMiZ** [comment]
I am in this loop too :(

**Comment by svr333** [comment]
Did you also use a custom port?

**Comment by pakoito** [comment]
I am seeing that after AFK-ing for a while AudioBand "disconnects" from Spotify and I have to go to the app to restart it again. I don't know if it's related to the custom config. I'll wait until this gets patched to open a new ticket :D

Also no rushes, the Windows AudioSource is doing the trick for now.

Thank you for your work!!

**Comment by svr333** [comment]
That is the Idle Profile feature, you can disable it by going into settings -> AudioBand Settings -> Idle Profile Settings.
You can also edit the Idle Profile to include a play/pause button so you can start the player from the comfort of your taskbar.

**Comment by pakoito** [comment]
Oooooh shit. Good to know, good to know. Disabled now hahaha

**Comment by svr333** [comment]
Resolved in [455ddb4](https://github.com/AudioBand/AudioBand/commit/455ddb4ea81a2bf6a8541060c3f86d92c1002f91).
New redirect url is:
`http://localhost/callback` or `http://localhost:PORT/callback` if you use a custom port

**Comment by pakoito** [comment]
Many many thanks again!!!

**Comment by svr333** [comment]
Youre welcome :)
