### ISSUE TITLE
spotify gets muted after audioband enters idle mode

### ISSUE THREAD

**Issue by lollilol** [AudioBand/AudioBand#63]
im using audioband with spotify and everytime audioband enters idle mode (default after 500 seconds) it mutes my spotify

**Comment by svr333** [comment]
what version do you use because this issue should be fixed with v1.1.4

**Comment by lollilol** [comment]
![image](https://user-images.githubusercontent.com/38194372/164893228-c2defbfb-c50f-4fca-aa86-5db6c99bc2d9.png)

**Comment by svr333** [comment]
weird Ill take a look and see if I can replicate it myself, thanks for taking the time to report it

**Comment by svr333** [comment]
does it actually mute the audio in spotify or is it just visually in audioband only?

**Comment by svr333** [comment]
@lollilol I found the issue, to temporarily fix this until next release, you can disable the option `Clear Current Song Information`
![image](https://user-images.githubusercontent.com/35664724/164895709-ccb9e2c9-d60d-4725-a24f-ddda9b2b4ff0.png)

**Comment by svr333** [comment]
Resolved by 989138aaa1b22c7b2dc6283c5d8e16b2496befd4
