### ISSUE TITLE
Play button not working, forward and backward working fine

### ISSUE THREAD

**Issue by NiP-24** [AudioBand/AudioBand#66]
I was getting an infinite loop of browsers with a 404 code saying the requested resource is not found. I changed the Spotify polling interval to 0 which solved that issue in the short term, but this occurs again any time I hit the shuffle this occurs again in addition to the play/ pause not working, but skip works fine.

**Comment by svr333** [comment]
I havent heard this issue before.

What AudioBand version are you on? (go in Settings -> About (top right) and it should show there.
Do you have Spotify Premium?

**Comment by SenneVanRompaey** [comment]
@NiP-24

**Comment by NiP-24** [comment]
I ended up removing it and trying on a different computer, and it worked fine.

Still trying to replicate the issue, but it seems to only occur on that specific machine.
________________________________
From: Senne Van Rompaey ***@***.***>
Sent: Monday, May 30, 2022 8:30:09 AM
To: AudioBand/AudioBand ***@***.***>
Cc: Nick Palya ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [AudioBand/AudioBand] Play button not working, forward and backward working fine (Issue #66)


@NiP-24<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNiP-24&data=05%7C01%7Cnipalya%40crimson.ua.edu%7Ca64c4967bc50468100df08da4240850c%7C2a00728ef0d040b4a4e8ce433f3fbca7%7C0%7C0%7C637895142127275113%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=iOfscyje3nDNaLhlxViIjpgCAnOZDkSzuGpF8ET3v5M%3D&reserved=0> any updates?

**Comment by svr333** [comment]
odd, Im going to close this due to unable to recreate and possibly an external app causes the bug, if you do ever get the error again feel free to re-open or make a new issue!
