### ISSUE TITLE
Audio band won't show up on taskbar

### ISSUE THREAD

**Issue by Dm12e** [AudioBand/AudioBand#68]
0## Description
So I restarted my pc and now audio band won't launch
I did try reinstalling but that didn't work either 

## How To Reproduce
1. Right-click on the taskbar and 
2. go to toolbars
3. Select Audio band
4. and it won't show up (although I'm seeing Deskband host for Wpf)

## Version
 - Windows 10 pro 21H2 OSbuild: 19044.1706
 - Idk how the check that (Downloaded the installer on 2 June 2022

## Logs/Screenshots Attachment

[AudioBand.log](https://github.com/AudioBand/AudioBand/files/8820070/AudioBand.log)

https://user-images.githubusercontent.com/79558567/171540994-7962dc8a-7bba-4cf6-9bae-5d2540171db6.mov

If applicable, feel free to add screenshots to show us the issue.

**Comment by TechSupport26** [comment]
Can you try restarting File explorer in task manager

**Comment by Dm12e** [comment]
So i got a fix 
Let me explain what was the bug
- I didn't like the "Default" profile so I deleted it
- That was stupid
How to fix
- Use the installer to remove
- Go to %appdata%\audio band
- delete that folder
- install
- Fixed!!

**Comment by svr333** [comment]
Thanks for the report, I'll make sure so when you delete a profile audioband doesn't crash entirely!
(Sorry it took so long but I didnt seem to have gotten a notifcation)

**Comment by darrenmcentee** [comment]
> So i got a fix Let me explain what was the bug
> 
> * I didn't like the "Default" profile so I deleted it
> * That was stupid
>   How to fix
> * Use the installer to remove
> * Go to %appdata%\audio band
> * delete that folder
> * install
> * Fixed!!

Thanks for this @Dm12e, i had the same issue. Removing the profile manually sorted. Cheers!
