### ISSUE TITLE
Spotify doesn't open when minimized to tray

### ISSUE THREAD

**Issue by svr333** [AudioBand/AudioBand#7]
## Description
When you have the "Close button should minimize the Spotify window to the tray" setting enabled inside of Spotify, and you close the Spotify window, it will not re-open when double clicking on the AudioBand player.

I've already tried resolving this issue but was unable to do so successfully, we might have to open spotify by re-running its `.exe` or receive external help.

**Comment by davidfaraci** [comment]
+1

**Comment by svr333** [comment]
#58 Will fix this issue, but not if you installed Spotify through the Microsoft Store.
This is due to it being too much of a hassle.
