### ISSUE TITLE
Possible to display on other windows? Either in or outside the taskbar?

### ISSUE THREAD

**Issue by Sonny-Crockett** [AudioBand/AudioBand#73]
## Description of your Suggestion
Ability to choose which monitor's taskbar the player displays.

## Alternative Solutions
Either use some windows feature I am unaware of to display toolbar on non dominant monitor. 

## Extra (if applicable)
Maybe just a question, rather than a feature.

**Comment by TechSupport26** [comment]
You have to change the primary monitor in windows settings, I don't think this is something that can be implimented

**Comment by svr333** [comment]
What he said, sadly Windows disallows Toolbars on secondary displays, meaning it can only ever be placed on the primary monitor.

Regarding displaying it outside of the Taskbar, we are working on getting a Tray Icon in the bottom right to do that functionality, but beside that there isn't much planned for such a feature

**Comment by svr333** [comment]
Going to close as it is outside the scope of this project. I don't currently know of any tool/windows version that allows for this (sadly enough)
