### ISSUE TITLE
MusicBee: Minutes and seconds for song duration swapped

### ISSUE THREAD

**Issue by kestara** [AudioBand/AudioBand#75]
## Description
MusicBee: Minutes and seconds for song duration swapped. Progress bar uses swapped duration as the maximum value.

Moving the playhead to a time that does not exist in the song seeks to the start of the last/incomplete second.
If the elapsed time is greater than the expected duration, the playhead stalls at 100%.

## How To Reproduce
1. Song length label text format is **{length}** (the default on install)
2. Play any music in MusicBee with Audio source set to MusicBee. No effect if song is e.g. 4:04 long. 

## Version
 - Windows 10 Home N, version 21H2
 - AudioBand version 1.1.4

## Logs/Screenshots Attachment

![screenshot of the issue described above](https://i.imgur.com/2Sbpoow.png)

(bottom of the playhead being cropped is my fault and not related to the bug)

**Comment by TechSupport26** [comment]
This is a known issue and has been patched for the next release.
See bug-discussion in the discord server message sent from the 20/04/2022
Here is an image of before. (I don't have one for the fixed one.)
![unknown.png](https://user-images.githubusercontent.com/65631811/180648192-86b68697-1c02-488c-bba9-09e7b614d52e.png)

**Comment by svr333** [comment]
As mentioned above, was resolved (will be in next release)
