### ISSUE TITLE
Spotify not updating information after update

### ISSUE THREAD

**Issue by Mavoy** [AudioBand/AudioBand#78]
After the yesterday's update (to the version 1.20, I believe) AudioBand stopped updating Spotify information. The buttons and the progress bar are still working, but unfortunately I'm stuck on the first song I listened to when it comes to artist, album and the artwork.

MusicBee integration is working just fine, so it's a Spotify problem. I checked the app on developer dashboard but it's set up like before.

I should also probably note in advance, that it could be Spotify version problem, since I'm using downgraded 1.1.46.916.g416cacf1 and I don't wanna move on, since it's the last one with the old layout. I think a lot of people are in the same position, so I hope if it's not supported anymore, it's not a move on your part.

I've started using AB recently and I'm a fan of this app, so hopefully it will be fixed.

**Comment by TechSupport26** [comment]
Hi Mavoy, Can you send AudioBands log file, in the %temp% directory
Also in AudioBands settings can you try Force Refresh Authentication and see if that fixes Spotify.
Thanks.

**Comment by Mavoy** [comment]
Thank you for quick reply - I forced reauthenthication and it's fixed now, thank you :)

**Comment by TechSupport26** [comment]
No worries, you can also join the discord if you want to ask questions.

**Comment by svr333** [comment]
The version with the old UI (and the possibility to disable ads without premium) will always be supported from our side
This bug is something caused by Spotify as well, usually restarting the spotify app or forcing authentication will do the job

**Comment by Mavoy** [comment]
unfortunately, it's not over yet

this is excerpt from the log file, I think it's being repeated over and over again

2022-08-08 13:30:52.5341 | ERROR | AudioSource(Spotify) | SpotifyAPI.Web.APITooManyRequestsException: Zgłoszono wyjątek typu 'SpotifyAPI.Web.APITooManyRequestsException'.
   w SpotifyAPI.Web.Http.APIConnector.ProcessErrors(IResponse response)
   w SpotifyAPI.Web.Http.APIConnector.<DoRequest>d__31.MoveNext()
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w SpotifyAPI.Web.Http.APIConnector.<DoSerializedRequest>d__30`1.MoveNext()
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w SpotifyAPI.Web.Http.APIConnector.<SendAPIRequest>d__34`1.MoveNext()
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w SpotifyAudioSource.SpotifyAudioSource.<NotifyLike>d__123.MoveNext() w C:\Users\vanro\Documents\Programming\AudioBand\AudioBand\src\SpotifyAudioSource\SpotifyAudioSource.cs:wiersz 776
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w SpotifyAudioSource.SpotifyAudioSource.<UpdatePlayer>d__128.MoveNext() w C:\Users\vanro\Documents\Programming\AudioBand\AudioBand\src\SpotifyAudioSource\SpotifyAudioSource.cs:wiersz 895---START OF EXCEPTION---
SpotifyAPI.Web.APITooManyRequestsException: Zgłoszono wyjątek typu 'SpotifyAPI.Web.APITooManyRequestsException'.
   w SpotifyAPI.Web.Http.APIConnector.ProcessErrors(IResponse response)
   w SpotifyAPI.Web.Http.APIConnector.<DoRequest>d__31.MoveNext()
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w SpotifyAPI.Web.Http.APIConnector.<DoSerializedRequest>d__30`1.MoveNext()
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w SpotifyAPI.Web.Http.APIConnector.<SendAPIRequest>d__34`1.MoveNext()
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w SpotifyAudioSource.SpotifyAudioSource.<NotifyLike>d__123.MoveNext() w C:\Users\vanro\Documents\Programming\AudioBand\AudioBand\src\SpotifyAudioSource\SpotifyAudioSource.cs:wiersz 776
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w SpotifyAudioSource.SpotifyAudioSource.<UpdatePlayer>d__128.MoveNext() w C:\Users\vanro\Documents\Programming\AudioBand\AudioBand\src\SpotifyAudioSource\SpotifyAudioSource.cs:wiersz 895
---END OF EXCEPTION

"Koniec śladu stosu..." is Polish, Deepl translates it as "The end of the stack trace from the previous location where the exception occurred"

I'll try restarting the app though. I have to restart the computer for something else anyway.

**Comment by svr333** [comment]
when you go into settings, and then Spotify polling interval, what setting is it set to?

**Comment by Mavoy** [comment]
It's 1000

(restarting didn't change anything)

**Comment by svr333** [comment]
do you have Spotify premium?

**Comment by Mavoy** [comment]
I do have Premium, yes

**Comment by svr333** [comment]
Im confused, seeing as the error indicates that AudioBand `spams` Spotify with too many requests, but I have my polling interval set to 750 and I don't have this issue.

If you set your polling interval to a higher value, does it keep occurring? (1500 for example, or even 2000)

**Comment by perraup** [comment]
I can confirm that I have the exact same issue since the update. Songs update every five seconds and sometimes don't switch over. I've reinstalled the program, restarted my computer, changed the polling from 1000 to 750, 1500, and 2000. Nothing has worked.

**Comment by Mavoy** [comment]
did you try to actually  Force Refresh Authentication in settings? I've had some issues after but I gotta say, it ended on my part. I used it now for two days with no problems, the songs are changing with no issue.

**Comment by perraup** [comment]
I did try it and it didn't work. Interestingly, I just tried it again and I got this error message: INVALID_CLIENT: Invalid redirect URI. My client ID and my Client secret are still the same on both Audio Band and Spotify's dashboard, so I'm pretty confused.

**Comment by perraup** [comment]
I restarted my computer again and now I keep getting INVALID_CLIENT: Invalid redirect URI pages popping up in Microsoft Edge and the program doesn't work at all. This is baffling.

**Comment by perraup** [comment]
I discovered that my redirect url was http://localhost, so I changed it to http://localhost/callback. I also lowered my polling rate to 750 and it seems to be working now.

**Comment by svr333** [comment]
I've found out what the issue is, you need to update your authentication method, but you figured that out too

The like button uses an extra scope, and if you authentication is not redone, it will crash and fail to update the player.
**Steps to resolve it:**
1) make sure http://localhost/callback is set as a redirect url on the spotify dashboard
2) go into audioband settings => spotify => force refresh auth and click apply

**Comment by fishloveavril** [comment]
hi, I faced the same problem.
My audioband cannot update albumm song name and player, so I follow your solution:
1. make sure http://localhost/callback is set as a redirect url on the spotify dashboard
2. go into audioband settings => spotify => force refresh auth and click apply
I also lower polling rate to 750

but redirect cannot work, it keeps redirect and does not work.

Please help me to solve this : (

**Comment by TechSupport26** [comment]
Can you send AudioBands log file, in the %temp% directory?
Also, are you using Spotify as an audio source or windows 10

**Comment by fishloveavril** [comment]
Thank you for the reply!

update:
 
somehow, it works normally now, song name and singer will be updated automatically. 
Yes, I'm using Spotify premium.

**Comment by AshleyCheema** [comment]
Just wanted to add that I had the same issue where I would get redirected to 'INVALID_CLIENT: Invalid redirect URI' - So I added http://localhost:(8183)/callback to the Redirects URIs

**Comment by TechSupport26** [comment]
Did this fix the INVALID_CLIENT: Invalid redirect URL?

**Comment by AshleyCheema** [comment]
Yes that did fix the issue for me

**Comment by AshleyCheema** [comment]
Hello again, I've been using AudioBand all day and all of a sudden it's just stopped updating. I look to be getting a similar issue as stated above. I have tried restarting everything and starting from square one but I cannot seem to get it working again. It started around 3pm GMT. Will keep you updated if anything changes

```
2022-08-11 16:41:00.4477 | ERROR | AudioSource(Spotify) | SpotifyAPI.Web.APITooManyRequestsException: Exception of type 'SpotifyAPI.Web.APITooManyRequestsException' was thrown.
   at SpotifyAPI.Web.Http.APIConnector.ProcessErrors(IResponse response)
   at SpotifyAPI.Web.Http.APIConnector.<DoRequest>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SpotifyAPI.Web.Http.APIConnector.<DoSerializedRequest>d__30`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SpotifyAPI.Web.Http.APIConnector.<SendAPIRequest>d__34`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SpotifyAudioSource.SpotifyAudioSource.<NotifyLike>d__123.MoveNext() in C:\Users\vanro\Documents\Programming\AudioBand\AudioBand\src\SpotifyAudioSource\SpotifyAudioSource.cs:line 776
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SpotifyAudioSource.SpotifyAudioSource.<UpdatePlayer>d__128.MoveNext() in C:\Users\vanro\Documents\Programming\AudioBand\AudioBand\src\SpotifyAudioSource\SpotifyAudioSource.cs:line 895---START OF EXCEPTION---
SpotifyAPI.Web.APITooManyRequestsException: Exception of type 'SpotifyAPI.Web.APITooManyRequestsException' was thrown.
   at SpotifyAPI.Web.Http.APIConnector.ProcessErrors(IResponse response)
   at SpotifyAPI.Web.Http.APIConnector.<DoRequest>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SpotifyAPI.Web.Http.APIConnector.<DoSerializedRequest>d__30`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SpotifyAPI.Web.Http.APIConnector.<SendAPIRequest>d__34`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SpotifyAudioSource.SpotifyAudioSource.<NotifyLike>d__123.MoveNext() in C:\Users\vanro\Documents\Programming\AudioBand\AudioBand\src\SpotifyAudioSource\SpotifyAudioSource.cs:line 776
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SpotifyAudioSource.SpotifyAudioSource.<UpdatePlayer>d__128.MoveNext() in C:\Users\vanro\Documents\Programming\AudioBand\AudioBand\src\SpotifyAudioSource\SpotifyAudioSource.cs:line 895
---END OF EXCEPTION
```

**Comment by svr333** [comment]
out of interest, what is your polling value set to, @AshleyCheema?
ApiTooManyRequests indicates that AudioBand asks Spotify too often to update

**Comment by AshleyCheema** [comment]
@svr333 1000. I don't think I have ever changed it since I've been using the application which has been a while now. It would make sense that they would deny me from pinging the system as it could be considered spamming. Just find it a bit odd that it happens after a updated AB. Same thing happened when I upgraded my PC too, I had to create a new app to get AB working again.

**Comment by svr333** [comment]
It's probably too coincidental, maybe it has something to do with the update. The weird thing is just that my interval is set to 750 and I haven't had the TooManyRequestsExceptions in ages.

The only difference I can think of is that you might not have Spotify Premium, but even then a 1 second polling interval should be plenty to not hit the ratelimit.
I'll try to figure out a cause here but honestly I've got no clue what's wrong

**Comment by TechSupport26** [comment]
@AshleyCheema Can you reinstall AudioBand 1.2.0 please.

**Comment by AshleyCheema** [comment]
Hey @TechSupport26 although it did happen and I just repeated the steps I mentioned above, I also upped the Polling Rate to 2000 it has been fine since so currently all is working as intended.

**Comment by svr333** [comment]
This issue was prevented with [02ec9a7](https://github.com/AudioBand/AudioBand/commit/02ec9a7ceac0e94d707cf568c9c63dd66e33c6a1). Closing as stale
