### ISSUE TITLE
Support for MS App version of Spotify opening by double clicking

### ISSUE THREAD

**Issue by imaginarny** [AudioBand/AudioBand#82]
## Description of your Suggestion

Add support for MS App version of Spotify to be able to be opened on double click. Currently, only classic Win32 Spotify installation is supported, opening it by its exe in the installation path, which is inaccessible and located elsewhere in the case of the app.

The conversation started here https://github.com/AudioBand/AudioBand/issues/51#issuecomment-1222229724 and was later clarified https://github.com/AudioBand/AudioBand/issues/51#issuecomment-1222491676.

This is the related code that needs to be modified, possibly allowing the app to be opened by Spotify's own protocol `spotify://`.

https://github.com/AudioBand/AudioBand/blob/44d5e7744d894c3ed37c5c826c1debe6cf613897/src/AudioBand/UI/Toolbar/MouseBindingsViewModel.cs#L306-L307

---

Currently, I'm having a working version of it and will create a pull request accordingly.

**Comment by svr333** [comment]
Resolved by #83
