### ISSUE TITLE
iTunes not showing information or art on v1.2.0

### ISSUE THREAD

**Issue by danreeves** [AudioBand/AudioBand#88]
## Description
No long displays song information or album art for iTunes, Controls still work.

## How To Reproduce
1. Open iTunes
2. Play song
3. Controls work but no song info
4. Downgrading back to 1.1.4 resolves issue

## Version
 - Windows version Version `10.0.19044 Build 19044`
 - iTunes version Version `12.12.5.8`
 - AudioBand Version 1.2.0

**Comment by svr333** [comment]
Thank you for your report, I already fixed this issue a couple days ago but didn't release anything yet.
If you'd like [this is a working build](https://cdn.discordapp.com/attachments/870211206760255548/1019649616200867973/AudioBand.msi) with this fix (made this for someone who reported it in our Discord).

I will also try to get some more bugs done and release a new version on github in a few days with this bug fix in it.

**Comment by danreeves** [comment]
Thanks, I checked for other issues but not the commit history. Works great!

**Comment by svr333** [comment]
Cheers!
