### ISSUE TITLE
Liking Songs Not Working?

### ISSUE THREAD

**Issue by livejamie** [AudioBand/AudioBand#97]
I've restarted my computer and done a reauth to no avail. Any ideas?

Here's a gif of what happens:
![What Happens](https://i.imgur.com/om5MJM1.gif)
https://i.imgur.com/om5MJM1.gif

Using the latest version of Windows 11 and AudioBand, it's worked previously. What can I do to troubleshoot?\

Here's my log file:
[AudioBand.zip](https://github.com/AudioBand/AudioBand/files/10198065/AudioBand.zip)

**Comment by svr333** [comment]
The error that is logged is that Spotify is getting too many requests from your account, so I think it needs to cool down for a bit. 
Though it does seem we might have a bug where AudioBand spams the api too much, so I'll take a look and see if I can limit it for the next release.

**Comment by livejamie** [comment]
> The error that is logged is that Spotify is getting too many requests from your account, so I think it needs to cool down for a bit. Though it does seem we might have a bug where AudioBand spams the api too much, so I'll take a look and see if I can limit it for the next release.

Thank you, there's nothing else I'm using that would make API requests, so it's firmly likely that it's forming from AudioBand.

Do you want me to close this or does it help you for me to keep it open?

**Comment by TechSupport26** [comment]
What is your Spotify Poling Interval set to? If it is too low then you will get rate limited.

**Comment by livejamie** [comment]
> What is your Spotify Poling Interval set to? If it is too high then you will get rate limited.

1000, I don't think I set it to anything myself. What do you recommend?

**Comment by TechSupport26** [comment]
1000 is good. Generally, it can be set to 750 but I don't think that that is possible in your case at the moment. How long has this been happening and do you know if someone/something else may have your client secret for Spotify?

**Comment by svr333** [comment]
> Do you want me to close this or does it help you for me to keep it open?

You can keep it open, It's a good reminder, thanks for taking the time to make a report btw!
